name: nfdiv-cron
description: NFDIV cron jobs
home: https://github.com/hmcts/nfdiv-cron
apiVersion: v2
appVersion: "1.0"
version: 0.0.25
maintainers:
  - name: HMCTS NFDIV Team
dependencies:
  - name: job
    version: 2.2.0
    repository: oci://hmctsprod.azurecr.io/helm
